### ISSUE TITLE
Ambi Climate throwing new error in 1.3.0-Beta56

### ISSUE THREAD

**Issue by Aekung** [hirakujira/homebridge-ambiclimate-platform#3]
Hi,

Ambi Climate Plugin seems to throw new error after updating to Homebridge 1.3.0-Beta56. Here is the error.

```
[13/02/2021, 00:19:34] Received error for the plugin 'homebridge-ambiclimate-platform' from the characteristic 'Serial Number': Error: [Serial Number] characteristic must have a length of more than 1 character otherwise HomeKit will reject this accessory. Ignoring new value.
    at SerialNumber.Characteristic.validateUserInput (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1983:38)
    at SerialNumber.Characteristic.setValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1257:20)
    at AccessoryInformation.Service.setCharacteristic (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Service.ts:464:35)
    at new AmbiClimateAirConditionAccessory (/usr/local/lib/node_modules/homebridge-ambiclimate-platform/src/airconditionAccessory.ts:43:8)
    at AmbiClimatePlatform.discoverDevices (/usr/local/lib/node_modules/homebridge-ambiclimate-platform/src/platform.ts:114:11)
    at HomebridgeAPI.<anonymous> (/usr/local/lib/node_modules/homebridge-ambiclimate-platform/src/platform.ts:55:12)
    at HomebridgeAPI.emit (events.js:327:22)
    at HomebridgeAPI.signalFinished (/usr/local/lib/node_modules/homebridge/src/api.ts:275:10)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:125:14)
```

The plugin is not working after the error occurs. Do you also experiencing the same thing?

Thank you and looking forward to hearing from you.

**Comment by hirakujira** [comment]
Thanks for the report, please try to update and check whether this is fixed.

**Comment by Aekung** [comment]
> Thanks for the report, please try to update and check whether this is fixed.

sorry for the late reply.

Everything works as it should be now.

Thank you very much.
