### ISSUE TITLE
Cannot get temperature and humidity reading

### ISSUE THREAD

**Issue by nox1982** [hirakujira/homebridge-ambiclimate-platform#8]
First time install but could not get the reading.

**Logs:**

```
[7/19/2021, 5:38:25 PM] [AmbiClimatePlatform] Get ac current temperature failed.{"error_code":400,"errors":[{"message":"The request is not valid"}]}
[7/19/2021, 5:38:25 PM] [AmbiClimatePlatform] Get current relative humidity failed.{"error_code":400,"errors":[{"message":"The request is not valid"}]}
[7/19/2021, 5:38:25 PM] [AmbiClimatePlatform] Get current tempature failed.{"error_code":400,"errors":[{"message":"The request is not valid"}]}
```

**Plugin Config:**

```json
            "clientId": "8cb09bdd-dcde-441e-992a-xxx",
            "clientSecret": "8cb0ebd8-2b52-4077-b903-xxx",
            "username": "xxx",
            "password": "xxx",
            "showFeedbacks": true,
            "heaterCoolerMode": true,
            "accessories": [
                {
                    "roomName": "Living Room",
                    "locationName": "xxx"
                }
            ],
            "platform": "AmbiClimatePlatform"
```

**Screenshots:**

**Environment:**

* **Plugin Version**:  v1.1.6
* **Homebridge Version**: v1.3.4
* **Node.js Version**: v14.17.0
* **NPM Version**: v6.14.13
* **Operating System**: rPi4 docker container

**Comment by hirakujira** [comment]
Your config is correct. Maybe your client Id or secret  or your password have some problem.

**Comment by nox1982** [comment]
In the logs there was mentioned login successful though…possible because my homebridge running under docker container? I have limited knowledge on network setup.

**Comment by hirakujira** [comment]
The "login successful" message only checks basic login account/password, it doesn't really check the status I think. And you can run homebridge under docker, it's fine. I updated some part of code of login in v1.1.6, maybe I broke something. Could you try to downgrade to v1.1.5 and check whether it works?

**Comment by nox1982** [comment]
No luck on that. Still the same error message in log.

**Comment by hirakujira** [comment]
Then I believe it's your client Id / secret issue. I have two recommend for you to try:
1. Create a new client id and secret and try again
2. Try another homebridge plugin and check whether it works for you https://www.npmjs.com/package/homebridge-ambiclimate

**Comment by nox1982** [comment]
recreate new client id does not help too. I installed the other plugin and resulted the below error.

```
[7/19/2021, 10:00:02 PM] TypeError: Cannot read property 'value' of undefined
    at /homebridge/node_modules/homebridge-ambiclimate/index.js:87:57
    at /homebridge/node_modules/node-ambiclimate/node_modules/q/q.js:2055:17
    at runSingle (/homebridge/node_modules/node-ambiclimate/node_modules/q/q.js:137:13)
    at flush (/homebridge/node_modules/node-ambiclimate/node_modules/q/q.js:125:13)
    at processTicksAndRejections (internal/process/task_queues.js:77:11)
[7/19/2021, 10:00:02 PM] Got SIGTERM, shutting down Homebridge...
[7/19/2021, 10:00:03 PM] [homebridge-ambiclimate] This plugin slows down Homebridge. The read handler for the characteristic 'Current Temperature' was slow to respond! See https://git.io/JtMGR for more info.
[7/19/2021, 10:00:03 PM] [homebridge-ambiclimate] This plugin slows down Homebridge. The read handler for the characteristic 'Current Relative Humidity' was slow to respond! See https://git.io/JtMGR for more info.
[7/19/2021, 10:00:03 PM] [homebridge-ambiclimate] This plugin slows down Homebridge. The read handler for the characteristic 'On' was slow to respond! See https://git.io/JtMGR for more info.
[7/19/2021, 10:00:03 PM] [homebridge-ambiclimate] This plugin slows down Homebridge. The read handler for the characteristic 'Rotation Speed' was slow to respond! See https://git.io/JtMGR for more info.
```

**Comment by hirakujira** [comment]
It's same reason. There's something wrong with your login info. It's not due to the homebridge plugin itself.
